INSERT INTO usuario (nombre, condicion) VALUES
('Luke Skywalker', 'Caballero Jedi - Maestro de la Fuerza'),
('Princesa Leia Organa', 'Líder de la Alianza Rebelde - Senadora'),
('Han Solo', 'Contrabandista - Capitán del Halcón Milenario'),
('Darth Vader', 'Lord Sith - Comandante Imperial'),
('Yoda', 'Gran Maestro Jedi - Consejero'),
('Obi-Wan Kenobi', 'Caballero Jedi - Mentor'),
('Chewbacca', 'Copiloto Wookiee - Guerrero'),
('R2-D2', 'Droide Astromecánico - Navegador'),
('C-3PO', 'Droide de Protocolo - Traductor'),
('Lando Calrissian', 'Administrador de Ciudad Nube - General'),
('Boba Fett', 'Cazarrecompensas Mandaloriano'),
('Padmé Amidala', 'Ex Reina de Naboo - Senadora'),
('Mace Windu', 'Maestro Jedi - Miembro del Consejo'),
('Jabba the Hutt', 'Señor del Crimen de Tatooine'),
('Rey', 'Basurera de Jakku - Jedi en entrenamiento');

INSERT INTO medio (tipo_medio, descripcion) VALUES
('Holonet', 'Red galáctica de comunicación instantánea'),
('Comlink', 'Dispositivo personal de comunicación'),
('Mensajero Droide', 'Droide especializado en entrega de mensajes'),
('Señal de Fuerza', 'Comunicación telepática entre sensibles a la Fuerza'),
('Transmisor Subespacial', 'Para comunicaciones interestelares'),
('Pantalla de Proyección', 'Para comunicaciones visuales'),
('Alerta de la Base', 'Sistema de alerta de bases rebeldes/imperiales'),
('Mensaje en Astromech', 'Mensaje grabado en droides astromecánicos'),
('Señal de Auxilio', 'Transmisión de emergencia en todas las frecuencias'),
('Holograma', 'Mensaje tridimensional proyectado'),
('Pájaro Mensajero', 'Método tradicional en planetas primitivos'),
('Tabla de Datos', 'Dispositivo físico de almacenamiento de información'),
('Sonda Imperial', 'Dispositivo de reconocimiento y comunicación'),
('Código Binario', 'Comunicación directa entre droides'),
('Faro de Señal', 'Transmisor de largo alcance');

INSERT INTO notificacion (usuario_id, medio_id, mensaje, estado, fecha_envio) VALUES
(1, 1, 'La Estrella de la Muerte está operativa. Necesitamos atacar ahora.', 'enviada', '2023-05-04 10:30:00'),
(2, 2, 'Han, te necesito. El Imperio ha capturado nuestra base en Hoth.', 'leída', '2023-05-04 11:15:00'),
(3, 3, '¡Te debo una! - Lando', 'pendiente', '2023-05-04 12:00:00'),
(4, 4, 'Luke, yo soy tu padre. Únete a mí.', 'fallida', '2023-05-04 13:45:00'),
(5, 5, 'Cuando 900 años cumplas, tan bien no te verás. En Dagobah te espero.', 'enviada', '2023-05-04 14:20:00'),
(6, 6, 'Usa la Fuerza, Luke. Apunta al respirador.', 'leída', '2023-05-04 15:10:00'),
(7, 7, '¡Arrrggghhh! (¡Alerta! Tropas imperiales acercándose)', 'enviada', '2023-05-04 16:05:00'),
(8, 8, 'Bip bip bop bip (Código de autodestrucción activado)', 'leída', '2023-05-04 17:30:00'),
(9, 9, '¡Oh querida! Las probabilidades de sobrevivir son de 3720 a 1.', 'pendiente', '2023-05-04 18:15:00'),
(10, 10, 'Cambio de plan. Rescaten a Han de la Ciudad Nube.', 'enviada', '2023-05-04 19:00:00'),
(11, 11, 'El cazarrecompensas Boba Fett ha capturado a Han Solo.', 'leída', '2023-05-04 20:45:00'),
(12, 12, 'Anakin, tienes miedo de perder a alguien, igual que yo.', 'fallida', '2023-05-04 21:30:00'),
13, 13, 'Ha llegado el momento. Arresten al Canciller.', 'enviada', '2023-05-04 22:10:00'),
(14, 14, '¡Han Solo! Ahora eres mío. Trae al Jedi.', 'pendiente', '2023-05-05 09:00:00'),
(15, 15, 'No estás sola. La Fuerza te acompaña siempre.', 'enviada', '2023-05-05 10:15:00');

INSERT INTO mision (nombre, descripcion, duracion, destino, fecha_inicio, fecha_fin, capacidad_max, estado) VALUES
('Destrucción de la Estrella de la Muerte', 'Ataque al reactor principal de la superarma imperial', 120, 'Estrella Muerte', '2023-05-04 08:00:00', '2023-05-04 10:00:00', 30, 'completada'),
('Rescate de la Princesa Leia', 'Infiltración en la Estrella de la Muerte para rescate', 45, 'Estrella Muerte', '2023-05-05 09:00:00', NULL, 4, 'activa'),
('Evacuación de Hoth', 'Escapar del ataque imperial en la Base Eco', 180, 'Hoth', '2023-05-06 06:00:00', '2023-05-06 09:00:00', 100, 'completada'),
('Rescate de Han Solo', 'Misión a Ciudad Nube para liberar a Han de Jabba', 90, 'Tatooine', '2023-05-07 10:00:00', NULL, 8, 'planificada'),
('Entrenamiento Jedi en Dagobah', 'Instrucción en los caminos de la Fuerza', 30, 'Dagobah', '2023-05-08 07:00:00', '2023-06-08 07:00:00', 2, 'activa'),
('Batalla de Endor', 'Ataque al generador de escudo de la segunda Estrella', 240, 'Endor', '2023-05-09 12:00:00', NULL, 50, 'planificada'),
('Diplomacia en Naboo', 'Negociaciones de paz con la Federación de Comercio', 60, 'Naboo', '2023-05-10 08:00:00', '2023-05-10 09:00:00', 10, 'cancelada'),
('Caza de Jedi', 'Localización y eliminación de Jedi sobrevivientes', 365, 'Galaxia', '2023-05-11 00:00:00', '2024-05-11 00:00:00', 1000, 'activa'),
('Construcción Estrella Muerte', 'Supervisión construcción superarma imperial', 730, 'Desconocido', '2023-01-01 00:00:00', '2024-12-31 00:00:00', 10000, 'activa'),
('Búsqueda de Planos Rebeldes', 'Recuperación de planos robados del Imperio', 15, 'Scarif', '2023-05-12 14:00:00', '2023-05-12 14:15:00', 10, 'completada'),
('Protección del Holocrón Jedi', 'Transporte de artefacto Jedi a lugar seguro', 48, 'Lothal', '2023-05-13 08:00:00', NULL, 5, 'activa'),
('Sabotaje Destructor Imperial', 'Infiltrarse y desactivar nave capital enemiga', 30, 'Espacio', '2023-05-14 20:00:00', '2023-05-14 20:30:00', 6, 'completada'),
('Recolección de Cristales Kyber', 'Minería de cristales para sables de luz', 120, 'Ilum', '2023-05-15 06:00:00', '2023-05-15 08:00:00', 20, 'planificada'),
('Diplomacia con los Ewoks', 'Establecer alianza con tribus nativas de Endor', 72, 'Endor', '2023-05-16 09:00:00', '2023-05-19 09:00:00', 15, 'planificada'),
('Investigación de Exegol', 'Explorar planeta secreto del Emperador', 168, 'Exegol', '2023-05-17 12:00:00', NULL, 12, 'activa');

INSERT INTO nave (mision_id, tipo, nombre) VALUES
(1, 'destructor sayayin', 'Halcón Milenario'),
(1, 'ataque rapidisimo', 'Ala-X Rojo Cinco'),
(1, 'ataque rapidisimo', 'Ala-Y Oro Dos'),
(2, 'destructor sayayin', 'Halcón Milenario'),
(2, 'la nave de anakin', 'Naboo N-1 Starfighter'),
(3, 'destructor sayayin', 'Transporte Rebelde GR-75'),
(3, 'motocicleta intergalactica', 'Speederbike 74-Z'),
(4, 'destructor sayayin', 'Halcón Milenario'),
(5, 'destructor sayayin', 'X-Wing de Luke'),
(6, 'destructor sayayin', 'Lanzadera Tydirium'),
(6, 'ataque rapidisimo', 'Ala-A Green Leader'),
7, 'la nave de anakin', 'Nave Real de Naboo'),
(8, 'destructor sayayin', 'Destructor Estelar clase Imperial'),
(9, 'destructor sayayin', 'Estrella de la Muerte'),
(10, 'destructor sayayin', 'Profundidad'),
(11, 'la nave de anakin', 'Fantasma'),
(12, 'ataque rapidisimo', 'B-Wing'),
(13, 'la nave de anakin', 'Nave de Transporte Jedi'),
(14, 'motocicleta intergalactica', 'Speederbike Imperial'),
(15, 'destructor sayayin', 'Nave de Mando de la Resistencia');

INSERT INTO carga (id_mision, tipo, peso, descripcion) VALUES
(1, 'explosivos', 500.00, 'Torpedos de protones para ataque al reactor'),
(1, 'combustible', 1000.50, 'Hipercombustible para cazas estelares'),
(2, 'equipo', 150.75, 'Trajes de stormtrooper para disfraz'),
(3, 'refugiados', 8000.00, 'Personal y equipo de la Base Eco'),
(4, 'armas', 300.25, 'Blásters y equipos de asalto'),
(5, 'suministros', 50.00, 'Raciones y equipo de supervivencia para Dagobah'),
(6, 'explosivos', 2000.00, 'Cargas de demolición para generador de escudo'),
(7, 'diplomático', 100.50, 'Documentos y regalos para la Federación'),
(8, 'equipo', 5000.00, 'Sondas de búsqueda y equipos de rastreo'),
(9, 'materiales', 1000000.00, 'Materiales de construcción para superarma'),
(10, 'datos', 0.50, 'Disco de datos con planos de la Estrella de la Muerte'),
(11, 'artefacto', 5.00, 'Holocrón Jedi sellado'),
(12, 'sabotaje', 200.00, 'Cargas magnéticas y equipos de hackers'),
(13, 'mineral', 1000.00, 'Cristales Kyber para sables de luz'),
(14, 'diplomático', 300.00, 'Obsequios y suministros para los Ewoks');

INSERT INTO reserva (id_usuario, id_mision, estado_reserva, comentarios) VALUES
(1, 1, 'completada', 'Líder del ataque al reactor principal'),
(2, 1, 'completada', 'Coordinación desde la sala de guerra'),
(3, 1, 'completada', 'Piloto del Halcón Milenario'),
(4, 8, 'activa', 'Comandante de la operación'),
(5, 5, 'activa', 'Instructor Jedi principal'),
(6, 2, 'confirmada', 'Acompañante para infiltración'),
(7, 3, 'completada', 'Piloto de transporte de evacuación'),
(8, 1, 'completada', 'Navegación y reparaciones'),
(9, 3, 'completada', 'Traducción e interacciones diplomáticas'),
(10, 6, 'confirmada', 'Líder del equipo de asalto'),
(11, 4, 'pendiente', 'Cazarrecompensas contratado por Jabba'),
(12, 7, 'cancelada', 'Senadora principal de las negociaciones'),
(13, 7, 'cancelada', 'Seguridad diplomática'),
(14, 4, 'pendiente', 'Anfitrión involuntario'),
(15, 15, 'activa', 'Líder de la expedición de exploración');